use waterpump;

CREATE TABLE waterpump(
    id INT PRIMARY KEY,
    amount_tsh FLOAT,
    date_recorded VARCHAR(255),
    funder VARCHAR(255),
    gps_height FLOAT,
    installer VARCHAR(255),
    longitude FLOAT,
    latitude FLOAT,
    wpt_name VARCHAR(255),
    num_private INT,
    basin VARCHAR(255),
    subvillage VARCHAR(255),
    region VARCHAR(255),
    region_code BIGINT,
    district_code BIGINT,
    lga VARCHAR(255),
    ward VARCHAR(255),
    population INT,
    public_meeting VARCHAR(255),
    recorded_by VARCHAR(255),
    scheme_management VARCHAR(255),
    scheme_name VARCHAR(255),
    permit VARCHAR(255),
    construction_year INT,
    extraction_type VARCHAR(255),
    extraction_type_group VARCHAR(255),
    extraction_type_class VARCHAR(255),
    management VARCHAR(255),
    management_group VARCHAR(255),
    payment VARCHAR(255),
    payment_type VARCHAR(255),
    water_quality VARCHAR(255),
    quality_group VARCHAR(255),
    quantity VARCHAR(255),
    quantity_group VARCHAR(255),
    source VARCHAR(255),
    source_type VARCHAR(255),
    source_class VARCHAR(255),
    waterpoint_type VARCHAR(255),
    waterpoint_type_group VARCHAR(255)
);